### ISSUE TITLE
Messfunktion: Messungen immer beibehalten

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#10]
Die Funktion 'Messungen beibehalten aktivieren/deaktivieren' kann entfallen bzw. es sollte konfigurierbar sein, dass:
- mehrere Messungen initial möglich sind
- die Funktion zum Aktivieren/Deaktivieren ausgeblendet wird

**Comment by danielhiscock** [comment]
It can now be configured whether the keep measurements functionality exists.
Configure accordingly:

`"bundles": {
        "dn_sketchingenhanced": {
            "Config": {
                "showKeepMeasurements": false,
                "multipleMeasurementsEnabled": true,
                "measurement": true,`
