### ISSUE TITLE
Pfeile werden als Striche dargestellt

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#101]
Vorgehen:
* Pfeil unterhalb von Polygonwerkzeuge auswählen
* Pfeile in die Karte zeichnen
* wenn man den Pfeil mit einem einfachen Klick abschließt, wird dieser als Pfeil gezeichnet
* wenn man den Pfeil mit Doppelklick beendet, wird dieser als Strich / Linie gezeichnet:
![image](https://user-images.githubusercontent.com/71440781/124086958-d70b9a00-da51-11eb-8fd3-0edb4d840cc1.png)

**Comment by matthiasstein** [comment]
Betrifft Version 2.x des Bundles, die nicht mehr weiterentwickelt wird.
