### ISSUE TITLE
Dezimalwerte für Konstruktionsparameter

### ISSUE THREAD

**Issue by JoergArnold** [conterra/mapapps-sketching-enhanced#106]
Für die Konstruktionsparameter:

- Radius
- Länge
- Winkel

können keine Dezimalwerte an die Konstruktionsfunktion übergeben werden.
Verwendet werden immer nur die ganzzahligen Anteile des Parameterwertes, die Dezimalwerte werden leider ignoriert.

Es wäre sehr praktisch, wenn man auch Dezimalzahlen (z.B. Radius = 10,5 m) als Konstruktionsparamer übergeben könnte.

Freundliche Grüße
Jörg Arnold

**Comment by matthiasstein** [comment]
Diese Funktion ist in der neuen Version 3.x noch nicht vorhanden. Ich werde den Issue auf lassen, damit dieser bei der Neuentwicklung der Funktion beachtet wird.

**Comment by sholtkamp** [comment]
Diese Funktion wurde bereits umgesetzt.
Die Länge von Polylinien und der Radius von Kreisen unterstützt in der Konstruktion Werte mit Dezimalen.
