### ISSUE TITLE
Einstellungen werden immer wieder zurückgesetzt

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#109]
Schritte
- Einstellungen öffnen
- die _Optionen Messungen_ beibehalten und _Zeichnungen einblenden_ deaktivieren
- Polygonwerkzeug aktivieren (reicht aus; es muss nichts gezeichnet werden)
- Einstellungen erneut öffnen

Ist
- die beiden Optionen sind wieder aktiviert

Soll
- die Optionen sind deaktiviert

**Comment by fbaldauf** [comment]
Die Option "Messungen beibehalten" gibt es nicht mehr.
Das Problem mit der Option "Zeichnungen einblenden" wurde durch 5c12e78317fe37f223956b90988291dac8f6e902 behoben
