### ISSUE TITLE
Cannot edit triangles in map.apps 4.12

### ISSUE THREAD

**Issue by sholtkamp** [conterra/mapapps-sketching-enhanced#110]
When trying to edit a triangle, the triangle is destroyed and a plethora of errors is thrown.

Reproduction steps:
1. Draw a triangle
2. Start editing mode
3. Select triangle
4. Move an orange vertex

**Comment by matthiasstein** [comment]
Betrifft Version 2.x des Bundles, die nicht mehr weiterentwickelt wird.
