### ISSUE TITLE
Objekt bearbeiten geht nicht in 4.11 und Edge-Browser

### ISSUE THREAD

**Issue by gedicb** [conterra/mapapps-sketching-enhanced#111]
Ist in der app.json (4.11) ein GROUND-Layer definiert, funktioniert das Werkzeug Objekt bearbeiten nicht mehr. Getestet mit Edge 93. Im Firefox treten diese Probleme nicht auf.

**Comment by kknoppe** [comment]
Ich habe das Problem auch unter 4.12 beobachten können. Statt das Objekt auszuwählen wird bei nach der Auswahl eines Polygons ein Punkt an die geklickte Stelle gezeichnet.
![image](https://user-images.githubusercontent.com/86719076/143550643-9eea692c-8870-4441-956b-d7516977c8ef.png)
In der Konsole wird der gleiche Fehler wie bei #137 angezeigt.

**Comment by kknoppe** [comment]
Das Tool funktioniert auch nur genau einmal. Es lässt sich danach nicht noch einmal aktivieren. Es funktioniert erst wieder richtig nachdem man ein neues Objekt in die Karte gezeichnet hat.

**Comment by matthiasstein** [comment]
Betrifft Version 2.x des Bundles, die nicht mehr weiterentwickelt wird.
