### ISSUE TITLE
Text labels won't draw when special characters are used

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#112]
A text label won't draw when the € sign is used. Other special characters ($, %) work fine.

**Comment by fbaldauf** [comment]
Dieser Bug kann mit der Version 2.2.0 nicht (mehr) nachgestellt werden

**Comment by marcwilkes** [comment]
In map.apps 4.11 ist der Fehler zu beobachten. Der Fehler tritt mit map.apps 4.12 aber nicht mehr auf. Daher können wir wohl auf eine Behebung verzichten.
