### ISSUE TITLE
Konstruktion Linie: Linienlänge wird nicht berücksichtigt

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#114]
*Vorgehen:*
* Linienkonstruktion öffnen
* Linienlänge auf 1000 m und Winkel auf 90 ° setzen
* Linien erzeugen

*IST:*
* die erzeugten Linien haben alle nicht die Länge von 1000 m sondern +/- 630 m
![image](https://user-images.githubusercontent.com/71440781/138855710-0bd50f90-d242-48e5-bc0f-6024f6299bb6.png)

*SOLL:*
* die Linien sollten eine Länge von 1000 m haben

**Comment by matthiasstein** [comment]
Betrifft Version 2.x des Bundles, die nicht mehr weiterentwickelt wird.
