### ISSUE TITLE
Einstellung "Messungen beibehalten"

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#116]
*Vorgehen:*
* im Dialog auf Einstellungen gehen
* "Messungen beibehalten" deaktivieren
* auf beliebiges Zeichenobjekt im Dialog wechseln
* auf Einstellungen gehen

*IST:*
* "Messungen beibehalten" ist aktiviert

*SOLL:*
* die zuvor vorgenommenen Einstellungen sollten beibehalten werden

(ist im Zusammenhang mit https://github.com/conterra/mapapps-sketching-enhanced/issues/117 zu betrachten)

**Comment by danielhiscock** [comment]
The settings option has been removed completely. If this is desired in the future it can be requested / implemented as an improvement
