### ISSUE TITLE
Messungen beibehalten entfernen

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#117]
Die Option "Messungen beibehalten" unterhalb von Einstellungen ist obsolet.

Diese Option kann entfernt werden.

(ist im Zusammenhang mit https://github.com/conterra/mapapps-sketching-enhanced/issues/116 zu betrachten

**Comment by danielhiscock** [comment]
The settings option has been removed completely. If this is desired in the future it can be requested / implemented as an improvement
