### ISSUE TITLE
Messfunktion: Auch Punkte berücksichtigen

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#12]
Die Messfunktion sollte dahingehend erweitert werden, dass die Punktkoordinaten berechnet und dargestellt werden. Hier ein Beispiel aus Linie 3:
![image](https://user-images.githubusercontent.com/69294548/89618966-64b82700-d88d-11ea-9795-65535fdf2c88.png)

Eine gute Ergänzung wäre noch die Möglichkeit zur Auswahl des RBS, in dem die Darstellung erfolgen soll.

**Comment by danielhiscock** [comment]
I have added the coordinate enhancement:
![image](https://user-images.githubusercontent.com/69298410/90147712-c2afa780-dd82-11ea-86dc-aeef392ce9c3.png)

I have also added the associated configuration like the old bi_sketching:
`         "MeasurementController": {
                "decimalPlacesMeter": 1,
                "decimalPlacesKiloMeter": 2,
                "pointSRS": "4326",
                "pointCoordPlaces": "3",
                "pointCoordUnitSymbolX": "°E",
                "pointCoordUnitSymbolY": "°N",
                "srs":{
                    "geodetic": [
                        4326,
                        3857,
                        4258
                    ],
                    "planar": [
                        2398,
                        2399,
                        25832,
                        25833,
                        31466,
                        31467,
                        31468,
                        31469
                    ]
                }
         }`
