### ISSUE TITLE
Bezeichnung "Objekte löschen"

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#121]
Unterhalb von Weitere Werkzeuge befindet sich das Werkzeug "Ausgewählte Objekte löschen".

Diese Bezeichnung ist verwirrend, da man mit dem Werkzeug immer nur ein zuvor ausgewähltes Objekt löschen kann.

Hier gibt es verschiedene Möglichkeiten zur Optimierung:
* Singular anstatt Plural (Ausgewähltes Objekt löschen)
* anstatt das Objekt zuvor zum Bearbeiten auszuwählen, direkt die Funktion "Objekt löschen" wählen, die ein Objekt durch draufklicken löschen

**Comment by fbaldauf** [comment]
Das Löschen funktioniert nun auch bei einer Mehrfachselektion. @ClaudiaBruns , kannst du dieses Ticket noch einmal neu bewerten?

**Comment by ClaudiaBruns** [comment]
Löschen funktioniert auch mit der Mehrfach Selektion. Allerdings gibt es die unter  #149 beschriebene Einschränkung.
Ich würde das Ticket jedoch an dieser Stelle schließen und den Punkt #149 separat betrachten
