### ISSUE TITLE
Messfunktion: Rückgängig und Abbrechen ist fehlerhaft

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#13]
**Teilstrecken bleiben in der Karte sichtbar, wenn die Funktion 'Rückgängig' genutzt wird**
1) Zeichnen eines Polygons:
![image](https://user-images.githubusercontent.com/69294548/89620877-9979ad80-d890-11ea-830d-fee40f2d8401.png)

2) Lezten Schritt Rückgängig machen:
![image](https://user-images.githubusercontent.com/69294548/89620911-b2825e80-d890-11ea-8a81-85813a07838d.png)

**Beim Abbrechen der Zeichnung**
- bleiben die Messwerte in der Karte und
- das Zeichenwerkzeug ist nicht mehr aktiv, obwohl es im Dialog noch aktiv dargestellt wird. Eine Karteninteraktion ist gar nicht mehr möglich (auch kein Pan), bis das Werkzeug deaktiviert wird.

**Comment by mkrage-ct** [comment]
Die Funktionen "Undo", "Redo" und "Cancel" wurden im Bezug auf das Messen überarbeitet und funktionieren jetzt wie erwartet. Beim "Rückgängig"-Machen des letzten Schritts wird die zugehörige Messung entfernt und beim "Wiederholen" des Schritts erneut angezeigt. Beim Abbrechen werden alle Messungen des zuletzt gezeichneten Objekts entfernt und das Sketching-Tool wieder aktiviert.
