### ISSUE TITLE
Messfunktion: Labels are static and do not change at different map scales (known issue?)

### ISSUE THREAD

**Issue by danielhiscock** [conterra/mapapps-sketching-enhanced#14]
When creating a shape with measurement, the labels are not reactive to scale changes. Perhaps at larger scales the font could be hidden?

![image](https://user-images.githubusercontent.com/69298410/89992050-03c19200-dc85-11ea-83dc-29e75cbd0c8c.png)

![image](https://user-images.githubusercontent.com/69298410/89992164-310e4000-dc85-11ea-96cb-abc72249fd1b.png)

**Comment by marcwilkes** [comment]
I'd leave this as is and would not change the current behaviour.
