### ISSUE TITLE
Zeichnen wird nach erstem Objekt beendet

### ISSUE THREAD

**Issue by kknoppe** [conterra/mapapps-sketching-enhanced#141]
**Schritte**
- einen Geometrietyp auswählen (z.B. Polygon)
- ein Objekt zeichnen und abschließen
- erneut in die Karte klicken um ein zweites Objekt zu zeichenen

**Erwartetes Ergebnis**
- der erste Stützpunkt wird gesetzt

**Tatsächliches Ergebnis**
- die Standard-Kartenfunktion wird ausgeführt (hier: Popup)

![image](https://user-images.githubusercontent.com/86719076/143549062-15596ee0-cb24-42f3-94cd-43c198fb428b.png)

Ich habe den Fehler mit dem neuesten Chrome nachstellen können, er tritt jedoch nicht immer auf. Es scheint das gleiche Timing-Problem wie bei #137 zu sein.

**Comment by fbaldauf** [comment]
@kknoppe Kannst du das mit der neusten Snapshot aus dem Nexus noch einmal gegentesten?

**Comment by kknoppe** [comment]
Ich habe gerade mit der neusten Version getestet (2.2.5) und kann den Fehler nicht mehr nachstellen. Ich kann mehrere Objekte direkt nacheinander zeichnen.
