### ISSUE TITLE
Selektion zu Mehrfachselektion

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#149]
*Vorgehen:*
* mehrere Sketching-Objekte einzeichnen
* ein Objekt auswählen
* zusätzlich ein weiteres Objekt auswählen, so das zwischen dem neuen und dem alten Objekt noch mehrere Objekte liegen

*IST:*
* es wird ein Rechteck über die beiden Objekte gezogen
* Objekte, die sich in dem Rechteck befinden, aber nicht selektiert wurden, lassen sich nicht mehr auswählen
und können somit nicht mit gelöscht, verschoben oder skaliert werden
![image](https://user-images.githubusercontent.com/71440781/147073365-0a68a6a6-b0e4-444d-acb3-b121938e2dc8.png)

(in dem Screenshot ist der grüne Punkt nicht mit selektiert, er würde nicht mit gelöscht oder verschoben werden)

*SOLL:*
es sollte eine Möglichkeit geben, auch Objekte zu selektieren, die sich bereits in der Fläche des Rechtecks befinden

**Comment by matthiasstein** [comment]
Betrifft Version 2.x des Bundles, die nicht mehr weiterentwickelt wird.
