### ISSUE TITLE
Textfarbe: Schieberegler lässt sich initial nicht bewegen

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#151]
Der Schieberegler für die Farbe lässt sich erst bewegen, wenn zuvor mit der Maus einmal in die 2D-Farbpalette geklickt wurde.
![image](https://user-images.githubusercontent.com/69294548/147751384-0872b4c8-1bf8-4528-a59c-2e4b2d3524c2.png)

**Comment by marcwilkes** [comment]
Gleiches gilt für die Farbe bei 'Text Blur'.

**Comment by matthiasstein** [comment]
Betrifft Version 2.x des Bundles, die nicht mehr weiterentwickelt wird.
