### ISSUE TITLE
Messungen werden beim Abbrechen einer Zeichnung nicht gelöscht

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#153]
Schritte
- Einen Linienzug mit aktiviert Messung zeichnen
- Während des Zeichnens mit ESC abbrechen

IST
- Die Linie wird durch das Abbrechen wieder gelöscht
- Die Messungen der Teilsegmente bleiben in der Karte erhalten 

SOLL
- Auch die Messungen sollen gelöscht werden

**Comment by matthiasstein** [comment]
Betrifft Version 2.x des Bundles, die nicht mehr weiterentwickelt wird.
