### ISSUE TITLE
Mehrfachselektion berücksichtigt nur die Beschriftung

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#159]
*Vorgehen:*
* Punkte mit Beschriftung (Messung) und Polygone zeichnen
![image](https://user-images.githubusercontent.com/71440781/154294573-c0729ea6-8a2b-4b96-9206-6371453c0e91.png)
* Polygon und den Punkt selektieren, indem man auf die Beschriftung klickt
* beides verschieben

*IST:*
die Beschriftung lässt sich ohne den Punkt verschieben
![image](https://user-images.githubusercontent.com/71440781/154294787-aeac4395-4668-4b75-a89a-14f9403d041a.png)

*SOLL:*
Die Beschriftung sollte sich nicht einzeln verschieben lassen

**Comment by matthiasstein** [comment]
Betrifft Version 2.x des Bundles, die nicht mehr weiterentwickelt wird.
