### ISSUE TITLE
Error after update to map.apps 4.13.1

### ISSUE THREAD

**Issue by schenardi** [conterra/mapapps-sketching-enhanced#165]
Error in dev environment after updating map.apps to 4.13.1

Console Log:
Logger.js:2 [ERROR] apprt/launch/BundleController: Unexpected error during getService('Bundle[81]-templatelayout-v4.13.1:{ACTIVE}','ServiceReference[dijit.Widget,dn_sketchingenhanced.Widget]-Bundle[3]-dn_sketchingenhanced-v2.3.1-SNAPSHOT:{ACTIVE}-{[object Object]}') UNSPECIFIED: Component.getService: Component 'Config' of bundle 'Bundle[3]-dn_sketchingenhanced-v2.3.1-SNAPSHOT:{ACTIVE}' unexpected exception during service get!
    cause of ACTIVATION_ERROR: Component._createComponentContext: Component 'Config' of bundle 'Bundle[3]-dn_sketchingenhanced-v2.3.1-SNAPSHOT:{ACTIVE}' component context can't be created, impl: 'SketchingEnhancedWidgetFactory'!
    cause of ACTIVATION_ERROR: Component._createComponentContext: Component 'Config' of bundle 'Bundle[3]-dn_sketchingenhanced-v2.3.1-SNAPSHOT:{ACTIVE}' component context can't be created, impl: 'SketchingEnhancedWidgetFactory'!
    cause of ILLEGAL_STATE_ERROR: service instances must not be used as reactive Vue properties (component Config from bundle Bundle[5]-dn_sketchingenhanced-construction-v2.3.1-SNAPSHOT:{ACTIVE} implementing dn_sketchingenhanced.SketchingConstructionModel)
    Function.b.<computed> [as illegalStateError]@https://dev.laixoversum.ch/invers/resources/jsregistry/root/apprt-core/4.13.1/Exception.js:1:337
Object.defineProperty@https://dev.laixoversum.ch/invers/resources/jsregistry/root/apprt/4.13.1/launch/BundleController.js:4:416
Function.defineProperty@<anonymous>
R@https://dev.laixoversum.ch/invers/resources/jsregistry/root/vue/2.6.14/vue.min.js:6:3350
new we@https://dev.laixoversum.ch/invers/resources/jsregistry/root/vue/2.6.14/vue.min.js:6:6641
Ce@https://dev.laixoversum.ch/invers/resources/jsregistry/root/vue/2.6.14/vue.min.js:6:7001
Object.set [as constructionModel]@https://dev.laixoversum.ch/invers/resources/jsregistry/root/vue/2.6.14/vue.min.js:6:7589
Cn.dn.set [as constructionModel]@https://dev.laixoversum.ch/invers/resources/jsregistry/root/vue/2.6.14/vue.min.js:6:28430
Function.assign@<anonymous>
SketchingEnhancedWidgetFactory.createInstance@http://localhost:9090/js/bundles/dn_sketchingenhanced/SketchingEnhancedWidgetFactory.js:41:14
H @ Logger.js:2

**Comment by dpayk** [comment]
Aufgrund von Änderungen in der ArcGIS API for JavaScript, die von diesem Bundle intensiv genutzt wird, ist das Bundle aktuell leider nicht mit map.apps 4.13 und aufwärts kompatibel. Eine Lösung dazu wird aktuell evaluiert. Wenn Interesse an der Beteiligung an einer Weiter- oder ggf. Neu-Entwicklung besteht, bitte gerne Kontakt zu uns aufnehmen.

**Comment by matthiasstein** [comment]
The new version 3.x is already available.
