### ISSUE TITLE
Löschen von Zeichnung im Querformat

### ISSUE THREAD

**Issue by Melanie-Kreis-Borken** [conterra/mapapps-sketching-enhanced#172]
Beim Tablet im Querformat wird die Zeichnung über die Löschfunktion nicht erkannt. 
Eine erstellte Zeichnung bleibt erhalten und die Meldung "Es liegt keine Zeichnung vor" wird angezeigt.

**Comment by matthiasstein** [comment]
Könnten Sie uns noch die Modellnummer des Tablets, die Betriebssystemversion und den verwendeten Browser nennen?

**Comment by Melanie-Kreis-Borken** [comment]
Es handelt sich um ein iPad Air 2, Softwareversion 15.7.6 sowohl im Browser Safari als auch im Firefox.

**Comment by sholtkamp** [comment]
Wir können dieses Problem nicht nachstellen. 
Wenn das Problem mit einer aktuellen map.apps version (4.16.0+) noch besteht, öffnen Sie dieses Issue gerne wieder. Dann können wir und das Problem gemeinsam ansehen.
