### ISSUE TITLE
Problems with adding texts with 3.4.4 (map.apps 4.12.3)

### ISSUE THREAD

**Issue by MartinOver2** [conterra/mapapps-sketching-enhanced#181]
Failed to load resource: the server responded with a status of 404 (404)
[esri.views.2d.engine.webgl.TextureManager] 

.../resources/apps/geoportal/fonts/arial-unicode-ms-regular/0-255.pbf
--> not found 

Installed the bundle via Developer Network Bundles Tool in the Manager.

**Comment by sholtkamp** [comment]
Cannot reproduce with map.apps 4.12.3 and bundle version 3.4.4.
Please reopen if issue persists.
