### ISSUE TITLE
Konstruierter Kreis nicht änderbar

### ISSUE THREAD

**Issue by gedicb** [conterra/mapapps-sketching-enhanced#183]
Erzeuge ich über eine Konstruktion einen Kreis kann dieses Objekt nicht mehr mit dem Werkzeug ‚Eine Zeichnung zum Editieren auswählen‘ ausgewählt und verändert werden. [map.apps 4.15.1/mapapps-sketching-enhanced 3.4.4]

Kreis konstruieren
![sketching_enh_04](https://github.com/conterra/mapapps-sketching-enhanced/assets/60434030/862e103c-5ba3-4029-a208-c864521a9fed)

Grafik kann nicht ausgewählt werden
![sketching_enh_05](https://github.com/conterra/mapapps-sketching-enhanced/assets/60434030/650a51ff-f37e-46ae-9f71-e406c9cba33e)

**Comment by matthiasstein** [comment]
Fixed in #185
