### ISSUE TITLE
Difference in measurements between map-labels and tool

### ISSUE THREAD

**Issue by dschlarmann** [conterra/mapapps-sketching-enhanced#184]
Using the mapapps-sketching-enhanced bundles (v. 3.4.4) I get some differences in the measurement details. Those differ between the map-labels and the information provided in the tool-window.
As far as I know the problem does **not** occur in SRS 3857, but at least in my tested SRS systems 25832, 25833 and 4326.

![image](https://github.com/conterra/mapapps-sketching-enhanced/assets/45598229/429bb581-fd7a-47fb-a4d7-a94dbf51e593)

**Comment by sholtkamp** [comment]
Fixed by PR #186
