### ISSUE TITLE
SRS changes breaks sketching functionality

### ISSUE THREAD

**Issue by dschlarmann** [conterra/mapapps-sketching-enhanced#187]
**Description:**
After changing the SRS while the Sketching-Window is open, it is not possible to create new sketches.
If SRS is changed before the Sketching-Window is opened, everything works fine.

**Reproduction:**
* While the sketching-window is open, change the SRS using the sdi_srschanger bundle 
* Draw a feature

**Result:**
Graphic is not drawn. It looks like that the click-listener is not connected anymore.

**Expected Result:**
"Graphic-Creation-Mode" is enabled. Graphic is created by clicking on the map.

**Comment by sholtkamp** [comment]
This requirement is too specific to be implemented by us.
If you choose to implement this yourself, we'll gladly incorporate it into the bundle.
