### ISSUE TITLE
Sketching Bundle crashes when trying to reshape a polygon-feature without measurements

### ISSUE THREAD

**Issue by kbor-maschmi** [conterra/mapapps-sketching-enhanced#190]
When trying to reshape a polygon without measurements the sketching bundle /app crashes and cannot be used anymore. 
Reshaping a polygon which was drawn with measurements is possible though.

**Comment by sholtkamp** [comment]
Cannot reproduce with map.apps 4.17.0 and bundle version 3.4.4.
What versions are you using?
