### ISSUE TITLE
Der Inhalt des Messen-Reiters ist nicht sichtbar

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#28]
![sketching_measurement](https://user-images.githubusercontent.com/69294548/92736597-b6ffd280-f37a-11ea-9bbd-9d61e5b2e928.png)

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-sketching-enhanced/commit/6bae99cc35fdbf5071f506317faac72361541638
