### ISSUE TITLE
[Objekt bearbeiten]: Labels von Messungen lassen sich editieren

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#35]
Seleting "Objekt bearbeiten" and clicking on an Objekt with Labels afterwards, it is possible to edit / manipulate the labels of the measurement:
![image](https://user-images.githubusercontent.com/71440781/93472398-db1c6000-f8f4-11ea-813c-a3a05b910745.png)

**Comment by danielhiscock** [comment]
To fix this I had to check if the update event graphics were of type "text" as well as checking if the text was measurement text. I had to add a flag for measurement tex objects

**Comment by danielhiscock** [comment]
@ClaudiaBruns this can be retested in the next release

**Comment by ClaudiaBruns** [comment]
positiv getestet am 26.10.2020
