### ISSUE TITLE
[Objekt bearbeiten]: Neue Label wenn Messungen aktiv

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#36]
Schritte:
* Polygon anlegen auswählen
* Messungen aktivieren
* Polygon anlegen
* Objekt bearbeiten auswählen
* an einer beliebigen Stelle in die Karte klicken
-> es werden Label mit folgenden Text angelegt: "Fläche: 0 m², Umfang 0 m"
![image](https://user-images.githubusercontent.com/71440781/93473999-0d2ec180-f8f7-11ea-9536-4c538ffa1487.png)

**Comment by danielhiscock** [comment]
There is a function in the MeasurementController called "_removeCorrelatedMeasurementTexts"
The funtion was taking all graphics that had symbols which can include text graphics as well as graphics that have text. I fixed this by only filtering graphics that are of types "text"

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 26.10.2020
