### ISSUE TITLE
[Objekt bearbeiten]: Messungen für Objekte ohne Messungen

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#37]
Schritte:
* Polygon anlegen auswählen
* Messen aktivieren
* Kantenlängen anzeigen aktivieren
* Polygon anlegen
-> Polygon wird mit Labeln der Messwerte angelegt
* Freihand-Polygon anlegen
-> Freihand-Polygon wird ohne Labeln angelegt
![image](https://user-images.githubusercontent.com/71440781/93475434-e1acd680-f8f8-11ea-9827-a34688bb5ef1.png)
* Objekt bearbeiten auswählen
* auf das Freihand-Polygon klicken und einen Stützpunkt verschieben
-> es werden Label am Freihand-Polygon angezeigt
-> die grüne Füllung verschwindet (ohne aktives Messen bleibt die Füllung erhalten)
![image](https://user-images.githubusercontent.com/71440781/93475671-318b9d80-f8f9-11ea-8354-2638fae32a7a.png)

**Comment by danielhiscock** [comment]
This was solved based on the solution from issue #36

**Comment by ClaudiaBruns** [comment]
positiv getestet am 26.10.2020
