### ISSUE TITLE
Darstellung im Dialog korrupt

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#38]
Die Darstellung innerhalb des Messen-Dialogs ist seltsam:
![image](https://user-images.githubusercontent.com/71440781/93477162-ef635b80-f8fa-11ea-9b96-6a2446cc153e.png)

Sowohl in FF ESR als auch in Chrome

**Comment by danielhiscock** [comment]
This is a BIMAPS specific issue. I had not added the styles in the bimaps project.

**Comment by matthiasstein** [comment]
Not related to the bundle.
