### ISSUE TITLE
[Polygon zeichnen]: Freihandfunktion bei Polygon unterbinden

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#39]
Schritte:
* Werkzeug Polygon auswählen 
* Linke Maustaste gedrückt halten und in der Karte zeichnen
-> obwohl man das Polygonwerkzeug ausgewählt hat, kann man Freihand-Polygone anlegen

**Comment by danielhiscock** [comment]
I have provided default modes as 'click' to the drawPolygon and drawPolyline tools. Now is is nolonger possible to freehand draw with those tools.

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 26.10.2020
