### ISSUE TITLE
[Messfunktion]: Messen für Kreis ermöglich

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#40]
Für einen Kreis sollten folgende Messfunktionen ermöglich werden:
* Radius oder Durchmesser
* Umfang

**Comment by danielhiscock** [comment]
now possible:
![Uploading image.png…]()

**Comment by ClaudiaBruns** [comment]
Auf Kreisen ist bislang keine Messunktion realisiert. Es werden keine Messergebnisse angezeigt.
Die Messfunktion lässt sich zwar aktivieren, aber es werden keine Messergebnisse angezeigt, weder in der Karte noch im Dialog
![image](https://user-images.githubusercontent.com/71440781/97177076-32380f00-1796-11eb-9ee2-3ecd98f654f8.png)

**Comment by danielhiscock** [comment]
Remove measurement tab for the circle, triangle

**Comment by danielhiscock** [comment]
The only tools that include measurement include: Polygon, square, polyline and point

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 04.03.2021
