### ISSUE TITLE
[Koordinatensystem]:Rechtschreibfehler

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#41]
Bei den unter Punkt auswählbaren Koordinatensystemen zur Anzeige bei Punkten steht "Gaus-"Krüger". bitte entweder "Gauss-Krüger" oder "Gauß-Krüger" verwenden
![image](https://user-images.githubusercontent.com/71440781/93480397-afea3e80-f8fd-11ea-8894-c4f593d50ca1.png)

**Comment by danielhiscock** [comment]
@ClaudiaBruns 
![image](https://user-images.githubusercontent.com/69298410/94279360-4517b380-ff4c-11ea-83b4-4a0eb169e082.png)
Can be re-tested in next release

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 26.10.2020
