### ISSUE TITLE
Settings Button - poor alignment; hover behavior

### ISSUE THREAD

**Issue by danielhiscock** [conterra/mapapps-sketching-enhanced#42]
The setting button is not properly aligned in the footer of the sketching window. Also, when the pointer is hovered over the button, a darker background is shown:
![image](https://user-images.githubusercontent.com/69298410/93740504-e6200a80-fbea-11ea-976d-bf59e38f5c33.png)

**Comment by danielhiscock** [comment]
I have fixed the alignment of the button:
![image](https://user-images.githubusercontent.com/69298410/108370504-033e2100-71fd-11eb-87a5-7cc24aa94c2e.png)

**Comment by ClaudiaBruns** [comment]
Positiv getestet für die Demo App am 18.03.2021
