### ISSUE TITLE
[Flächenmessung]: Flächenmessung für Polygone inkonsistent

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#46]
Schritte:
* Zeichenwerkzeug öffnen
* Polygon zeichnen aktivieren
* Messung aktivieren
* mehrere Polygone zeichnen

-> die angezeigten Ergebnisse stimmen nicht immer mit den Labeln zum Flächeninhalt überein
![image](https://user-images.githubusercontent.com/71440781/97176286-023c3c00-1795-11eb-99c1-a335eef38517.png)

**Comment by ClaudiaBruns** [comment]
hängt mit #54 zusammen

**Comment by danielhiscock** [comment]
See issue #54

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 18.03.2021
