### ISSUE TITLE
[Dreieck]: Messungen werden in Karte aber nicht im Dialog angezeigt

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#47]
Schritte:
- Zeichenwerkzeug öffnen
- Dreieck zeichnen aktivieren
- Messung aktivieren
- Dreieck zeichnen

-> Das Dreieck wird in der Karte mit Fläche und Umfang angezeigt. Im Dialog werden jedoch keine Werte angezeigt.
-> Entweder das Messen für Dreiecke deaktivieren oder die Werte ebenfalls im Dialog anzeigen
![image](https://user-images.githubusercontent.com/71440781/97178329-9c04e880-1797-11eb-9399-623467ac6d9c.png)

**Comment by marcwilkes** [comment]
Bei aktivierter Kantenbeschriftung werden nur zwei von drei Seiten beschriftet.

**Comment by danielhiscock** [comment]
This has been resolved with issue #40

**Comment by ClaudiaBruns** [comment]
Wenn Messungen aktiviert sind, werden für Dreiecke weiterhin Messungen in der Karte aber nicht im Dialog angezeigt:
![image](https://user-images.githubusercontent.com/71440781/111606677-cb180700-87d7-11eb-82c8-7d44d27429be.png)

**Comment by danielhiscock** [comment]
Currently this just has to be configured in both the measurement configurations settings:

https://github.com/conterra/mapapps-sketching-enhanced/blob/2264cfa733eca4f91475c05b00f1c0ead35ea1e8/src/main/js/apps/sample/app.json#L73

and the tab can be disabled sepatately. It would be ideal if this could be combined. so for now I will set this ticket as 'enhancement'

**Comment by danielhiscock** [comment]
The triangle measurements is now recorded in the panel.

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 21.06.2021
