### ISSUE TITLE
Style are set to default in the dialog when switching tools

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#50]
**Steps**

- Go to polyline tool and change line styles
- Draw graphic
![sketching_line](https://user-images.githubusercontent.com/69294548/98348309-da609a00-2018-11eb-9d29-2d523d5bcf16.png)

- Got to polygon tool
--> symbol style are set to default
--> drawn graphic uses previously set line styles
![sketching_polygon](https://user-images.githubusercontent.com/69294548/98348423-04b25780-2019-11eb-97e6-6766789d0652.png)

**Expected**
First, the style settings in the dialog should always reflect the style that is used to draw a graphic.
Second, one of the following should apply
1. Each tool (or toolgroup) has it's own style settings that are kept even after switching forth and back to other tools.
2. In case style definitions, e.g. line styles, are used across all tools, the dialog should correctly show that style when switching tools.

I prefer the first solution, i.e. a user can define different styles for line, point and polygon tools and they are 'remembered' when switching tools back and forth.

**Comment by marcwilkes** [comment]
Another note: When switching between polygon tools, the styles are always set back to default as well. I would expect to use the same style definitions across all polygon tools (Polygon, Freehand Polygon, Rectange, Triange, Circle,...).

**Comment by danielhiscock** [comment]
Now the symbol settings will be persisted within each tool group. For example if symbol settings are changed for the polygon tool, the same settings will be applied to the circle tool

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 18.03.2021
