### ISSUE TITLE
change label for area and circumference

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#51]
I woul like to configure the label for area and circumference that is shown in the map via the app.json (and even be able to choose to don't label those values at all):
![measurement_labels](https://user-images.githubusercontent.com/69294548/98370002-23751600-203a-11eb-9bbb-248b45d9dedc.png)

E.g., a customer just wants to see 'F: ...' und 'U: ...' or maybe even only the values.

Minor issue in en-locale: Currently, the label in the map is 'circumference', the label in the dialog is 'Perimeter': This should be the same by default.

**Comment by danielhiscock** [comment]
@marcwilkes this is now configurable in the app.json as follows:
`"dn_sketchingenhanced-measurement": {
            "Config": {
                "disabledMeasurementTools": [...],
                "measurementLabels": {
                    "de-de": {
                        "totalLength": "G",
                        "area": "F",
                        "circumference": "U"
                    },
                    "en-en": {
                        "totalLength": "Total length",
                        "area": "Area",
                        "circumference": "Perimeter"
                    }
                }
...`
**result**:
![image](https://user-images.githubusercontent.com/69298410/108495773-7c934d80-72a9-11eb-91f5-07e3fe6897d8.png)
