### ISSUE TITLE
Messungen auf Texten entfernen

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#52]
Schritte:

* Zeichenwerkzeug öffnen
* Texte zeichnen aktivieren

-> für Texte gibt es die Option Messung -> bitte Messung für Texte entfernen 
![image](https://user-images.githubusercontent.com/71440781/105370501-ee716c00-5c03-11eb-9b18-872a7dcb365d.png)

**Comment by danielhiscock** [comment]
This is resolved along with #40 and #57

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 18,03,2021
