### ISSUE TITLE
Use geodesic methods of geometry engine

### ISSUE THREAD

**Issue by matthiasstein** [conterra/mapapps-sketching-enhanced#54]
Currently, only the normal methods from the geometry engine are used. This leads to incorrect measurements for certain reference systems.

**Comment by ClaudiaBruns** [comment]
siehe auch #46 und #56 56

**Comment by danielhiscock** [comment]
I have included geodesic calculations as well as fixed an aggregation issue

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 18.03.2021
