### ISSUE TITLE
Pfeile für Größeneinstellung innerhalb von Firefox doppelt

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#55]
**Vorgehen:**
* Sketching Tool innerhalb von Firefox öffnen
* auf die Zahl zum Ändern der Größe klicken

-> innerhalb von Firefox werden 2 Pfeile zum Verändern der Größe dargestellt:
![image](https://user-images.githubusercontent.com/71440781/106449587-65202c00-6484-11eb-8a33-a2d9217ea0f0.png)

Anmerkung:
die doppelten Pfeile treten im Menü für die Konstruktion auf:

![image](https://user-images.githubusercontent.com/71440781/106758032-5460e900-6631-11eb-92ed-147cc97ddee4.png)

**Comment by danielhiscock** [comment]
fixed in firefox:
![image](https://user-images.githubusercontent.com/69298410/108481979-2cac8a80-7299-11eb-9e74-b40517f952eb.png)

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 18.03.2021
