### ISSUE TITLE
[Linienmessung]: Linienmessung inkonsistent

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#56]
Schritte:

- Zeichenwerkzeug öffnen
- Linienzug zeichnen aktivieren
- Messung aktivieren
- Linienzug zeichnen

-> die angezeigten Ergebnisse stimmen nicht mit den Labeln zur Länge überein
![image](https://user-images.githubusercontent.com/71440781/106737454-faebc080-6616-11eb-9bac-bced49fc8ca9.png)

**Comment by ClaudiaBruns** [comment]
hängt mit #54 zusammen

**Comment by danielhiscock** [comment]
Duplicate - See issue #54

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 18.03.2021
