### ISSUE TITLE
[Linienmessung]: Freihand Linienzug erhält keine Messwerte

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#57]
Schritte:

- Zeichenwerkzeug öffnen
- Freihand Linienzug zeichnen aktivieren
- Messung aktivieren
- Freihand Linienzug zeichnen

-> in der Karte und im Dialog werden keine Messwerte angezeigt
![image](https://user-images.githubusercontent.com/71440781/106750178-c92f2580-6627-11eb-87fd-dbca0eefdba1.png)

**Comment by danielhiscock** [comment]
Remove measurement tab from freehandpolyline/polygon

**Comment by danielhiscock** [comment]
The only tools that include measurement include: Polygon, square, polyline and point

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 18.03.2021
