### ISSUE TITLE
[Text]: GUI nicht schön

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#58]
Browser: FF ESR 

Schritte:

- Zeichenwerkzeug öffnen
- Text zeichnen aktivieren
- auf Schriftgröße klicken

-> die angezeigten Subdialog enthält überflüssige Pfeile
![image](https://user-images.githubusercontent.com/71440781/106754791-ae5faf80-662d-11eb-826d-8b07d1ef48cb.png)

**Comment by danielhiscock** [comment]
improvement in firefox:
![image](https://user-images.githubusercontent.com/69298410/108481574-a6904400-7298-11eb-8d74-93418ceb57d9.png)

**Comment by ClaudiaBruns** [comment]
Positiv getestet für die Demo App am 18.03.2021
