### ISSUE TITLE
[Text]: GUI Textrotation schwer lesbar

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#59]
Browser: FF ESR 

Schritte:

- Zeichenwerkzeug öffnen
- Text zeichnen aktivieren
- auf Textrotation klicken

-> die angezeigten Subdialog ist schwer lesbar und enthält überflüssige Pfeile
![image](https://user-images.githubusercontent.com/71440781/106755234-2a59f780-662e-11eb-9926-524fef28fc35.png)

**Comment by danielhiscock** [comment]
improvement in firefox:
![image](https://user-images.githubusercontent.com/69298410/108481495-91b3b080-7298-11eb-8055-cda2240ad606.png)

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 18.03.2021
