### ISSUE TITLE
Measurements (Labels) are not coupled with the graphics

### ISSUE THREAD

**Issue by danielhiscock** [conterra/mapapps-sketching-enhanced#61]
Measurement text graphics often remain when graphics are edited or removed.
![image](https://user-images.githubusercontent.com/69298410/108507268-5b872880-72ba-11eb-825d-db3fad723c94.png)

**Comment by ClaudiaBruns** [comment]
Das Verhalten tritt weiterhin so auf.
Getestet am 18.03.2021

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 26.05.2021
