### ISSUE TITLE
Remove old autocast symbols

### ISSUE THREAD

**Issue by matthiasstein** [conterra/mapapps-sketching-enhanced#62]
The bundle uses many old autocast symbols:

```json
"snapPolygonObjectSymbol": {
	"type": "esriSFS",
	"color": [
		102,
		205,
		0,
		100
	],
	"outline": {
		"color": [
			0,
			0,
			0,
			255
		],
		"style": "esriSLSSolid",
		"type": "esriSLS",
		"width": 1.3
	},
	"size": 16,
	"style": "esriSFSSolid",
	"xoffset": 0,
	"yoffset": 0
}
```

This is the correct way:

```json
"snapPolygonObjectSymbol": {
	"type": "simple-fill",
	"color": [
		102,
		205,
		0,
		100
	],
	"outline": {
		"color": [
			0,
			0,
			0,
			255
		],
		"style": "solid",
		"type": "simple-line",
		"width": 1.3
	},
	"style": "solid"
}
```

In addition, some attributes are used that are not supported by the respective symbol. For example _xoffset_ for a SimpleFillSymbol.

More information: https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-Symbol.html

**Comment by danielhiscock** [comment]
@matthiasstein the new symbol autocast types appear to not be supported as well:
![image](https://user-images.githubusercontent.com/69298410/108691732-1a7e5680-74fc-11eb-8434-5df290887106.png)
