### ISSUE TITLE
Dezimaltrennzeichen noch nicht überall korrekt

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#66]
Im Dialog wird das Dezimaltrennzeichen für den Umfang noch nicht entsprechend der Locale angezeigt. Gleiches gilt für die Werte in der Karte:
![image](https://user-images.githubusercontent.com/69294548/109290158-8972ec80-7827-11eb-8a46-7320c3ca23a4.png)

IST
Es wird bei lang=de teilweise noch ein Punkt als Dezimaltrenner verwendet.

SOLL
Es muss bei lang=de ein Komma als Dezimaltrenner verwendet werden.
Zusätzlich kann die Optimierung umgesetzt werden, dass in der Karte auch die Tausendertrennzeichen dargestellt werden. Im Dialog ist dies bereits der Fall.

**Comment by danielhiscock** [comment]
![image](https://user-images.githubusercontent.com/69298410/110112712-652c8800-7db2-11eb-950b-acf1da5cf919.png)
Fixed

**Comment by ClaudiaBruns** [comment]
Positiv getestet am 26.05.2021
