### ISSUE TITLE
Messfunktion: Aktualisierung der Werte nach der Geometriebearbeitung fehlerhaft

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#7]
Wenn bei der Geometriebearbeitung Stützpunkte entfernt werden, dann werden die Messwerte der nicht mehr vorhandenen Kanten nicht gelöscht.

![image](https://user-images.githubusercontent.com/69294548/89617330-4e5c9c00-d88a-11ea-9e91-aba36b2949aa.png)

**Comment by mkrage-ct** [comment]
Wenn nun Stützpunkte entfernt werden, so werden die entsprechenden Messungen entfernt und die neuen, zur Geometrie passenden, Messungen angezeigt.
