### ISSUE TITLE
Construction only uses planarLength

### ISSUE THREAD

**Issue by matthiasstein** [conterra/mapapps-sketching-enhanced#71]
The construction code only uses geometryEngines planarLength and not geodesicLength-method. This leads to wrong constructions when using WGS84 (wkid: 4326) or Web Mercator.

https://github.com/conterra/mapapps-sketching-enhanced/blob/11f75ff88e01e76b65b858d155252dfc52bce3d9/src/main/js/bundles/dn_sketchingenhanced-construction/SketchingConstructionInfo.js#L65

https://github.com/conterra/mapapps-sketching-enhanced/blob/11f75ff88e01e76b65b858d155252dfc52bce3d9/src/main/js/bundles/dn_sketchingenhanced-construction/SketchingConstructionInfo.js#L89

**Comment by danielhiscock** [comment]
resolved. I have added the geodesicLength calculation as well
