### ISSUE TITLE
Undo & redo does not work in object edit mode

### ISSUE THREAD

**Issue by matthiasstein** [conterra/mapapps-sketching-enhanced#72]
While editing an object undo & redo leads to very strange results. Sometimes the whole feature is deleted.

**Comment by danielhiscock** [comment]
The undo and redo handling was coded in two different components for some reason (MeasurementController.js and SketchHandler.js).

**Comment by danielhiscock** [comment]
fixed with the latest changes "redesign dn_sketchingenhanced-measurement bundle"
