### ISSUE TITLE
Formatierungen werden nicht gespeichert

### ISSUE THREAD

**Issue by alessandrobeck** [conterra/mapapps-sketching-enhanced#76]
Bei unserer Implementierung des Tools mit map.apps 4.11 werden die Formatierungen wie Füllungsfarbe oder Linienstärke wieder zurückgesetzt, sobald das Werkzeug gewechselt wird (z.B. von Polygon auf Rechteck). Dies verhält sich auch bei minimaler Konfiguration in app.json so.

`{
   "load": {
      "allowedBundles": [
         "system",
         "templatelayout",
         "template-seasons",
         "theme-everlasting",
         "toolset",
         "map-init",
         "notifier",
         "dn_sketchingenhanced",
         "dn_vuecolor"
      ]
   },
   "bundles": {
      "map-init": {
         "Config": {
            "map": {
               "basemap": [
                  {
                     "id": "streets",
                     "title": "Streets",
                     "url": "https://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer",
                     "type": "AGS_TILED",
                     "visible": true
                  }
               ]
            },
            "view": {
               "viewmode": "2D",
               "extent": {
                  "xmin": 600000,
                  "ymin": 5800000,
                  "xmax": 1700000,
                  "ymax": 7600000,
                  "spatialReference": 3857
               }
            }
         }
      },
      "toolset": {
         "ToolsetManager": {
            "toolsets": [
               {
                  "id": "my_toolset",
                  "title": "My Toolset",
                  "tools": [
                     "sketchingEnhancedWidgetToggleTool"
                  ],
                  "container": "map",
                  "windowType": "dropdown",
                  "position": {
                     "rel_l": 150,
                     "rel_t": 250
                  }
               }
            ]
         }
      }
   }
}`

**Comment by danielhiscock** [comment]
#76 FIXED - In der neuesten Version scheint dies kein Problem mehr zu sein.
version 2.1.5
