### ISSUE TITLE
Uncaught ReferenceError: temporary is not defined

### ISSUE THREAD

**Issue by matthiasstein** [conterra/mapapps-sketching-enhanced#79]
https://github.com/conterra/mapapps-sketching-enhanced/blob/154141255a5ad83961b373e98c7ff0dac5ea2d77/src/main/js/bundles/dn_sketchingenhanced-measurement/MeasurementController.js#L352

**Comment by danielhiscock** [comment]
fixed with the latest changes "redesign dn_sketchingenhanced-measurement bundle"
