### ISSUE TITLE
Messfunktion: Es sollte konfigurierbar sein, ob die Kantenlängen von Polygonen in der Karte dargestellt werden.

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#8]
Die Darstellung von Teilstrecken und Kanten soll im Dialog aktivert bzw. deaktiviert werden können. Die Voreinstellungen sollen konfigurierbar sein. Idealerweise kann man dies für jeden Geometrietyp individuell einstellen, so dass z.B. Teilstrecken bei Linienzügen dargestellt werden, einzelne Kanten eines Polygons aber nicht.

**Comment by mkrage-ct** [comment]
Innerhalb des Sketching Dialogs öffnet sich beim Aktivieren des Messens nun ein weiterer Abschnitt mit zwei Checkboxen, in denen eingestellt werden kann, ob Linien und Kantenlängen angezeigt werden sollen oder nicht. Die Voreinstellungen dazu sind über die app.json konfigurierbar.
