### ISSUE TITLE
Using the wrong method for area calculation in SketchingConstuctionInfo.js

### ISSUE THREAD

**Issue by matthiasstein** [conterra/mapapps-sketching-enhanced#80]
In the case of a geodesic area, the planarArea method is used. The other way round, the geodesicArea method is used if it is a planar area.

**Comment by matthiasstein** [comment]
https://github.com/conterra/mapapps-sketching-enhanced/blob/154141255a5ad83961b373e98c7ff0dac5ea2d77/src/main/js/bundles/dn_sketchingenhanced-construction/SketchingConstructionInfo.js#L69

**Comment by danielhiscock** [comment]
(/) fixed with the latest changes
