### ISSUE TITLE
screenUtils sind in map.apps 4.12 nicht mehr nutzbar

### ISSUE THREAD

**Issue by dpayk** [conterra/mapapps-sketching-enhanced#88]
In map.apps 4.12 wird man 

`{createScreenPoint} from "esri/core/screenUtils"`

nicht mehr importieren können in `https://github.com/conterra/mapapps-sketching-enhanced/blob/master/src/main/js/bundles/dn_sketchingenhanced-command/SketchingSelection.js`.

Es gibt hierfür aber neue Methoden, siehe https://developers.arcgis.com/javascript/latest/functionality-matrix/#esrigeometry.

**Comment by matthiasstein** [comment]
@danielhiscock can you replace the usage of this class?
