### ISSUE TITLE
Messfunktion: Werkzeuge einschränken, sobald Messen aktiv ist

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-sketching-enhanced#9]
Die Messfunktion ist nicht für alle Zeichenwerkzeuge sinnvoll, z.B. bei Pfeilen. Daher sollte es konfigurierbar sein, welche Zeichenwerkzeuge noch auswählbar sind, sobald die Messfunktion aktiviert wird. Zudem sollte die Darstellung von Teilstrecken und -kanten bei Freihandzeichnungen unterbunden werden.

**Comment by danielhiscock** [comment]
Now a simple configuration can be made to indicate which tools are to be disabled when measurement is enabled:
`"dn_sketchingenhanced-measurement": {
            "Config": {
                "disabledMeasurementTools": [
                    "drawarrowtool",
                    "drawfreehandpolygontool",
                    "drawfreehandpolylinetool",
                    "constructionpolylinetool"
                ],
                "decimalPlacesMeter": 1,
                "decimalPlacesKiloMeter": 2,
                "showLineMeasurementsAtPolylines": true,`
