### ISSUE TITLE
Nicht lauffähig in map.apps 4.11.2-SNAPSHOT

### ISSUE THREAD

**Issue by sholtkamp** [conterra/mapapps-sketching-enhanced#91]
Das Bundle kann in map.apps 4.11.2-SNAPSHOT nicht genutzt werden.

Ursache: 
- Die Esri Klasse screenUtils.js wird nicht gefunden
- Das Modul dn_sketchingenhanced-command wird nicht gefunden

**Comment by dpayk** [comment]
Siehe auch https://github.com/conterra/mapapps-sketching-enhanced/issues/88.

**Comment by matthiasstein** [comment]
Duplicate of #88
