### ISSUE TITLE
Dreieck: Kantenlängen werden bei bei Bearbeitung angelegt 

### ISSUE THREAD

**Issue by ClaudiaBruns** [conterra/mapapps-sketching-enhanced#96]
**Vorgehen:**
* im Zeichentool für Polygone die Messungen und Anzeige der Kantenlängen aktivieren
* Dreieck auswählen
* Dreieck anlegen
![image](https://user-images.githubusercontent.com/71440781/122769681-0f1e1a80-d2a5-11eb-860d-adc1d211cf19.png)
* Objekt bearbeiten aktivieren
* Dreieck auswählen

*IST:*
sobald man das Dreieck ausgewählt hat, werden die Kantenlängen an die Schenkel des Dreiecks geschrieben:
![image](https://user-images.githubusercontent.com/71440781/122769953-4bea1180-d2a5-11eb-990c-f6fd90d291df.png)
geht man aus dem Modus bearbeiten, bleiben die Labels für die Kantenlängen erhalten

*SOLL:*
Dreiecke sollten keine Kantenlängen erhalten

**Comment by matthiasstein** [comment]
Betrifft Version 2.x des Bundles, die nicht mehr weiterentwickelt wird.
