### ISSUE TITLE
Sketchings nach Laden aus App-Zuständen werden nicht erkannt

### ISSUE THREAD

**Issue by danielhiscock** [conterra/mapapps-sketching-enhanced#97]
**Vorgehen.**

Auskunfts App öffnen
Sketching öffnen
Linienzug mit Messungen anlegen .> Linie wird mit Labeln angezeigt
App Zustand "Linie" speichern
App zustand laden
Sketching öffnen
**IST:**

der Button "Weitere Werkzeuge" ist ausgegraut
![image](https://user-images.githubusercontent.com/69298410/122773241-78ebf380-d2a8-11eb-9e0e-2e55354acb87.png)

**Comment by danielhiscock** [comment]
Resolved from ticket #98 commit

**Comment by kknoppe** [comment]
Der Fehler tritt mit Version 2.3,2 immer noch auf. Die fehlerhafte Codezeile ist:
`sketchingGraphicLayer.graphics = graphics;`
in bundles/dn_sketchingenhanced-tools/SketchingParameterResolver.js in der Funktion decodeURLParameter.

Richtig ist:
`sketchingGraphicLayer.addMany(graphics);`

**Comment by matthiasstein** [comment]
Betrifft Version 2.x des Bundles, die nicht mehr weiterentwickelt wird.
